apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    chart.version: {{ .Chart.Version }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: "wil42/playground:v1"
        ports:
        - containerPort: 80